endpoints:
  - name: Google
    group: external
    url: "https://www.google.com"
    interval: 30s
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 1000"
      
  - name: GitHub-API
    group: external
    url: "https://api.github.com"
    interval: 30s
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 2000"
      
  - name: AWS-Health
    group: external
    url: "https://health.aws.amazon.com"
    interval: 60s
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 3000"

web:
  port: 8080
