name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.0

    - name: Terraform format check
      working-directory: terraform/environments/dev
      run: terraform fmt -check

    - name: Terraform validate
      working-directory: terraform/environments/dev
      run: |
        terraform init -backend=false
        terraform validate

  security:
    name: Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Build image
      working-directory: ./app
      run: docker build -t gatus:latest .

    - name: Run Trivy scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'gatus:latest'
        format: 'table'
        severity: 'HIGH,CRITICAL'
        exit-code: '0'

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [validate, security]
    
    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2

    - name: Login to ECR
      run: aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin 475641479654.dkr.ecr.eu-west-2.amazonaws.com

    - name: Build and push image
      working-directory: ./app
      run: |
        docker buildx build --platform linux/amd64 --load -t gatus-ecs-dev .
        docker tag gatus-ecs-dev:latest 475641479654.dkr.ecr.eu-west-2.amazonaws.com/gatus-ecs-dev:${{ github.sha }}
        docker tag gatus-ecs-dev:latest 475641479654.dkr.ecr.eu-west-2.amazonaws.com/gatus-ecs-dev:latest
        docker push 475641479654.dkr.ecr.eu-west-2.amazonaws.com/gatus-ecs-dev:${{ github.sha }}
        docker push 475641479654.dkr.ecr.eu-west-2.amazonaws.com/gatus-ecs-dev:latest